language: node_js
node_js:
  - '8'
matrix:
  include:
  - os: linux
    env: TEST=true
    sudo: required
  - os: osx
    env: TEST=false
before_install:
  - if $TEST; then npm install -g data-cli@0.7.0; else echo 'skipping this script...'; fi
install:
  - if $TEST; then data --version; else echo 'skipping this script...'; fi
script:
  - if $TEST; then npm update -g data-cli; else echo 'skipping this script...'; fi
after_success:
  - if $TEST; then data --version; else echo 'skipping this script...'; fi
  - if $TEST; then data help; else echo 'skipping this script...'; fi
after_script:
  - chmod ugo+x npm-yarn-installable.sh
  - ./npm-yarn-installable.sh
