os:
  - linux
  - osx
language: node_js
node_js:
  - '9'
  - '8'
  - '7'
before_install:
  - npm install -g data-cli@0.7.0
install:
  - data --version
script:
  - npm update -g data-cli
after_success:
  - data --version
  - data help
after_script:
  - data info https://pkgstore.datahub.io/90998f7f90e086bd5fc7c9075dfda43b/basic-csv/comma-separated_csv/data/f4f7de54ccaaffa6ac0e5fe804653bf2/comma-separated_csv.csv
