language: node_js
node_js:
  - '8'
matrix:
  include:
  - os: linux
    env: TEST=true
  - os: osx
    env: TEST=false
before_install:
  - if [ $TEST ]; then npm install -g data-cli@0.7.0; fi
install:
  - if [ $TEST ]; then data --version; fi
script:
  - if [ $TEST ]; then npm update -g data-cli; fi
after_success:
  - if [ $TEST ]; then data --version; fi
  - if [ $TEST ]; then data help; fi
after_script:
  - chmod ugo+x npm-yarn-installable.sh
  - ./npm-yarn-installable.sh
