language: node_js
node_js:
  - '8'
matrix:
  include:
  - os: linux
    env: TEST=true
  - os: osx
    env: TEST=false
before_install:
  - env $TEST npm install -g data-cli@0.7.0
install:
  - env $TEST data --version
script:
  - env $TEST npm update -g data-cli
after_success:
  - env $TEST data --version
  - env $TEST data help
after_script:
  - chmod ugo+x npm-yarn-installable.sh
  - ./npm-yarn-installable.sh
